INFO:root:Starting Logging ....1
WARNING:root:This a warning log ----1
ERROR:root:Error found at line ....12
INFO:root:Starting Logging ....1
WARNING:root:This a warning log ----1
ERROR:root:Error found at line ....12
INFO:root:Starting Logging ....1
WARNING:root:This a warning log ----1
ERROR:root:Error found at line ....12
INFO:root:Starting Logging ....1
WARNING:root:This a warning log ----1
INFO:root:Starting Logging ....1
WARNING:root:This a warning log ----1
ERROR:root:Error found at line ....12
2021-04-04 15:57:14,347 Starting Logging ....1
2021-04-04 15:57:15,125 This a warning log ----1
2021-04-04 15:57:15,523 Error found at line ....12
2021-04-04 16:02:02,710 Error occured 
2021-04-04 16:02:02,710 division by zero
Traceback (most recent call last):
  File "<ipython-input-12-f39df9593052>", line 4, in <module>
    a = b/a
ZeroDivisionError: division by zero
2021-04-04 16:11:38,501 critical line 
2021-04-04 16:12:23,386 critical line 
2021-04-04 16:26:31,128 Enter 3 numbers separated by space to get their sumation
2021-04-04 16:26:36,351 Entered numbers are 12,8,10
2021-04-04 16:27:01,808 Enter 3 numbers separated by space to get their sumation
2021-04-04 16:27:05,421 Entered numbers are 12,8,10
2021-04-04 16:27:05,421 Sum of numbers is 30
2021-04-04 16:28:34,684 Enter 3 numbers separated by space to get their sumation
2021-04-04 16:28:38,173 Entered numbers are 12,3,54
2021-04-04 16:28:38,173 Sum of numbers is 69
